version: 0.2
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      # - cd terraform
      # - terraform init
      # - terraform plan
      # - terraform apply -auto-approve






# version: 0.2

# phases:
#   install:
#     commands:
#       - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
#       - unzip terraform_1.6.6_linux_amd64.zip
#       - mv terraform /usr/local/bin/
#   build:
#     commands:
#      - aws sagemaker create-processing-job \
#           --processing-job-name timesheet-dq-$CODEBUILD_BUILD_ID \
#           --app-specification ImageUri=763104351884.dkr.ecr.$AWS_REGION.amazonaws.com/sagemaker-processing-container:latest \
#           --role-arn $SAGEMAKER_ROLE_ARN \
#           --processing-resources ClusterConfig={InstanceType=ml.m5.large,InstanceCount=1,VolumeS


