version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: timesheet-dq-processing
    IMAGE_TAG: latest
    AWS_REGION: eu-west-1

phases:
  pre_build:
    commands:
      - ls -l
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Docker image pushed successfully"

      # OPTIONAL: trigger SageMaker Pipeline
      - echo "Starting SageMaker Pipeline execution"
      - aws sagemaker start-pipeline-execution --pipeline-name timesheet-edfx-dev --region $AWS_REGION

artifacts:
  files:
    - '**/*'
